 _format_version: "3.0"
 _transform: true

 services:
  - host: localhost
    name: kafka_producer
    port: 9092
    protocol: http
    routes:
    - name: kafka_producer_route
      paths:
      - /
      strip_path: true
